env:
  - EKS_BUILD_TYPE=debug
  - EKS_BUILD_TYPE=release

install:
  - sudo add-apt-repository --yes ppa:alexey-ivanov/qtcreator
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qbs qt5-default clang libstdc++5
  - qbs setup-toolchains --detect
  - qbs setup-qt /usr/bin/qmake qt
  - qbs config profiles.qt.baseProfile clang
  - qbs profile:qt ${EKS_BUILD_VARIANT}
