env:
  - EKS_BUILD_TYPE=debug
  - EKS_BUILD_TYPE=release

install:
  - sudo add-apt-repository --yes ppa:alexey-ivanov/qtcreator
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qbs qt5-default clang
  - qt5-qmake -query

script:
  - "./EksBuild/BuildAndTestDebian.sh"
