install:
  - sudo add-apt-repository --yes ppa:alexey-ivanov/qtcreator
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  - sudo apt-get install qbs qtbase5-dev

script:
  - "./EksBuild/BuildAndTestDebian.sh"