env:
  - EKS_BUILD_TYPE=debug
  - EKS_BUILD_TYPE=release

install:
  - git clone https://github.com/jorj1988/rbmake.git ~/rbmake

script:
  - mkdir build
  - cd build
  - ~/rbmake/rbmake.rb build ..
  - ~/rbmake/rbmake.rb test ..
