#ifndef EKSDEBUG_GLOBAL_H
#define EKSDEBUG_GLOBAL_H

#include "XGlobal.h"

#if defined(EKSDEBUG_BUILD)
#  define EKSDEBUG_EXPORT X_DECL_EXPORT
#else
#  define EKSDEBUG_EXPORT X_DECL_IMPORT
#endif

#define X_ENABLE_APPLICATION_DEBUGGING

#endif // EKSDEBUG_GLOBAL_H
